const mealData = [
    {
        "title": "Bacon & Eggs",
        "mealType": "Breakfast",
        "id": 1,
        "date": "2025-03-20",
        "energy": 460,
        "protein": 25,
        "fat": 18,
        "carbs": 10,
    },
    {   
        "title": "Pasta with Meatballs",
        "mealType": "Lunch",
        "id": 2,
        "date": "2025-03-20",
        "energy": 600,
        "protein": 20,
        "fat": 10,
        "carbs": 30,
    },
    {
        "title": "Thai Curry & Rice",
        "mealType": "Dinner",
        "id": 3,
        "date": "2025-03-20",
        "energy": 800,
        "protein": 20,
        "fat": 15,
        "carbs": 40,
    },
    {
        "title": "Cashews",
        "mealType": "Snack",
        "id": 4,
        "date": "2025-03-20",
        "energy": 200,
        "protein": 10,
        "fat": 15,
        "carbs": 15,
    },
    {
        "title": "Oatmeal",
        "mealType": "Breakfast",
        "id": 5,
        "date": "2025-03-21",
        "energy": 300,
        "protein": 10,
        "fat": 5,
        "carbs": 25,
    },
    {   
        "title": "Taco Pie",
        "mealType": "Lunch",
        "id": 6,
        "date": "2025-03-21",
        "energy": 800,
        "protein": 25,
        "fat": 18,
        "carbs": 35,
    },
    {
        "title": "Pizza with Pineapple",
        "mealType": "Dinner",
        "id": 7,
        "date": "2025-03-21",
        "energy": 900,
        "protein": 20,
        "fat": 15,
        "carbs": 40,
    },
    {
        "title": "Cookies & Milk",
        "mealType": "Snack",
        "id": 8,
        "date": "2025-03-21",
        "energy": 200,
        "protein": 10,
        "fat": 15,
        "carbs": 15,
    },
    {
        "title": "Banana",
        "mealType": "Snack",
        "id": 8,
        "date": "2025-03-21",
        "energy": 120,
        "protein": 2,
        "fat": 0,
        "carbs": 10,
    },
    {
        "title": "Oatmeal & Protein Pudding",
        "mealType": "Breakfast",
        "id": 5,
        "date": "2025-03-21",
        "energy": 500,
        "protein": 20,
        "fat": 5,
        "carbs": 20,
    },
]

export default mealData;